const CATEGORIES = [
  { id: "painting-kits", name: "Painting Kits", icon: "fa-paint-roller" },
  { id: "hand-painted",  name: "Hand-Painted",  icon: "fa-paint-brush" },
  { id: "divine",        name: "Divine Idols",  icon: "fa-om" },
  { id: "wall-art",      name: "Wall Art",      icon: "fa-palette" },
  { id: "gifts",         name: "Gift Sets",     icon: "fa-gift" },
];

const SHOP_PRODUCTS = [
  {
    id: 1,
    name: "Hand-Painted Ganesha Figurine — Purple",
    price: 349,
    category: "divine",
    image: "images/ganesha-purple.jpg",   // ← REPLACE with your GitHub Pages image path
    gallery: [],
    description: "Lavender Ganesha hand-painted on terracotta.",
    details: "A serene Ganesha figurine sculpted and hand-painted in soft lavender with a pink crown. Each piece is one-of-a-kind.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 2,
    name: "Unicorn Magic — DIY Painting Set",
    price: 599,
    category: "painting-kits",
    image: "images/unicorn-magic.jpg",
    gallery: [],
    description: "6-piece unicorn & fairytale figures to paint.",
    details: "Six unpainted plaster figures — unicorn, mermaid tail, star, princess and more. Pop them out, paint and display.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 3,
    name: "Aarush Painting Kit — Farm Friends",
    price: 449,
    category: "painting-kits",
    image: "images/farm-friends.jpg",
    gallery: [],
    description: "Paint, pop & display your own farm animal.",
    details: "Comes with 1 pop figure, 6 acrylic paints, 1 paint brush and instructions. Safe for kids 3+. Dries in 20–30 minutes.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 4,
    name: "Tricolour Wooden Ganesha Set (Pack of 3)",
    price: 899,
    category: "divine",
    image: "images/wooden-ganesha-trio.jpg",
    gallery: [],
    description: "Three vibrant Ganeshas on hand-painted wooden blocks.",
    details: "A trio of festive Ganesha idols on hand-painted wooden plinths — perfect for a pooja shelf or housewarming gift.",
    stock: "Made to Order",
    featured: true,
  },
  {
    id: 5,
    name: "Little Monk on Lotus — Acrylic Painting",
    price: 1499,
    category: "wall-art",
    image: "images/little-monk.jpg",
    gallery: [],
    description: "Original acrylic painting on canvas board.",
    details: "A peaceful monk meditating on a pink lotus, framed by soft leaves. Hand-painted in acrylic. Signed by the artist.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 6,
    name: "Lotus Ganesha Wall Plate",
    price: 399,
    category: "hand-painted",
    image: "images/lotus-ganesha-plate.jpg",
    gallery: [],
    description: "Pocket-sized hand-painted Ganesha on a lotus plate.",
    details: "Tiny circular wall plate hand-painted with a Ganesha on a pink lotus mandala. Hang anywhere — entrance, pooja room, desk.",
    stock: "In Stock",
    featured: false,
  },
  {
    id: 7,
    name: "Aarush Painting Kit — Ocean Friends",
    price: 499,
    category: "painting-kits",
    image: "images/ocean-friends.jpg",
    gallery: [],
    description: "Sea-themed pop figures to paint at home.",
    details: "Turtle, dolphin, starfish, seahorse, fish — a whole ocean to bring to life. Includes paints, brush and instructions.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 8,
    name: "Aarush Mini Painting Kit + Keychain",
    price: 299,
    category: "gifts",
    image: "images/mini-kit-keychain.jpg",
    gallery: [],
    description: "Compact painting kit with a free keychain.",
    details: "Mini pop figures, 6 paint pots, brush and a cute pre-painted keychain. Perfect return gift or stocking filler.",
    stock: "In Stock",
    featured: false,
  },
];

const SHOP_CONFIG = {
  brand: "Aarush Art & Craft",
  brandShort: "Aarush",
  brandAccent: "Art & Craft",
  tagline: "Handmade with heart, from Chennai.",
  whatsapp: "919566087705",
  upiId: "9566087705@upi",
  payeeName: "Aarush Art & Craft",
  email: "pebblesenterprises21@gmail.com",
  phone: "+91 9566087705",
  address: "Chennai, Tamil Nadu, India",
  website: "https://aarushartcraft.store",
  instagram: "#",
  facebook: "#",
};
