const CATEGORIES = [
  { id: "painting-kits", name: "Painting Kits", icon: "fa-paint-roller" },
  { id: "hand-painted",  name: "Hand-Painted",  icon: "fa-paint-brush" },
  { id: "divine",        name: "Divine Idols",  icon: "fa-om" },
  { id: "wall-art",      name: "Wall Art",      icon: "fa-palette" },
  { id: "gifts",         name: "Gift Sets",     icon: "fa-gift" },
];

const SHOP_PRODUCTS = [
  {
    id: 1,
    name: "Hand-Painted Ganesha Figurine",
    price: 150,
    category: "divine",
    image: "image/ganesha-figurines.png",   // ← REPLACE with your GitHub Pages image path
    gallery: [],
    description: " Ganesha hand-painted on POP and pasted on MDF, coated for glossy look.",
    details: "A serene Ganesha figurine sculpted and hand-painted in soft lavender with a pink crown. Each piece is one-of-a-kind.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 2,
    name: "Unicorn Magic — DIY Painting Set",
    price: 99,
    category: "painting-kits",
    image: "image/unicorn-theme painting kit.png",
    gallery: [],
    description: "6-piece unicorn & fairytale figures to paint.",
    details: "Six unpainted plaster figures — unicorn, mermaid tail, star, princess and more. Pop them out, paint and display.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 3,
    name: "Aarush Painting Kit — Farm Friends",
    price: 99,
    category: "painting-kits",
    image: "image/farmfriends.png",
    gallery: [],
    description: "Paint, pop & display your own farm animal.",
    details: "Comes with 4 pop figure, 6 acrylic paints, 1 paint brush and instructions. Safe for kids 3+. Dries in 20–30 minutes.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 4,
    name: "Space - theme painting Kit",
    price: 99,
    category: "painting-kits",
    image: "image/spacetheme.png",
    gallery: [],
    description: "Beautiful Space theme POP painting kit with astronaut, earth and rocket",
    details: "Comes with 3 pop figure, 6 acrylic paints, 1 paint brush and instructions. Safe for kids 3+. Dries in 20–30 minutes.",
    stock: "Made to Order",
    featured: true,
  },
  {
    id: 5,
    name: "Little Monk on Lotus- Fridge magnet",
    price: 99,
    category: "hand-painted",
    image: "image/lotus bhuddha.jpg",
    gallery: [],
    description: "Original acrylic painting on mdf.",
    details: "A peaceful monk meditating on a pink lotus.. Hand-painted in acrylic. Fridge magnet, coated with glossy finish.Size - 2inch.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 6,
    name: "Lotus ganesha-fridge magnet",
    price: 89,
    category: "hand-painted",
    image: "image/lotus -Ganesha Fridge Magnet.png",
    gallery: [],
    description: "Pocket-sized hand-painted Ganesha on a lotus plate.",
    details: "Tiny circular wall plate hand-painted with a Ganesha on a pink lotus mandala. Fridge magnet.",
    stock: "In Stock",
    featured: false,
  },
  {
    id: 7,
    name: " Ocean Friends- Kit",
    price: 99,
    category: "painting-kits",
    image: "image/ocean-friends.png",
    gallery: [],
    description: "Sea-themed pop figures to paint at home.",
    details: "Turtle, dolphin, starfish, seahorse, fish — a whole ocean to bring to life. Includes paints, brush and instructions.",
    stock: "In Stock",
    featured: true,
  },
  {
    id: 8,
    name: "Flower ganesha figurines",
    price: 150,
    category: "divine",
    image: "image/flower-ganesha figurines.png",
    gallery: [],
    description: "Ganesha hand-painted on POP and pasted on MDF, coated for glossy look",
    details: "Unique and stylish ganesh,Each piece is one-of-a-kind.",
    stock: "In Stock",
    featured: false,
  },
];

const SHOP_CONFIG = {
  brand: "Aarush Art & Craft",
  brandShort: "Aarush",
  brandAccent: "Art & Craft",
  tagline: "Handmade with heart, from Chennai.",
  whatsapp: "919566087705",
  upiId: "9566087705@upi",
  payeeName: "Aarush Art & Craft",
  email: "pebblesenterprises21@gmail.com",
  phone: "+91 9566087705",
  address: "Chennai, Tamil Nadu, India",
  website: "https://aarushartcraft.store",
  instagram: "#",
  facebook: "#",
};
